In [48]:
import urllib.request
urllib.request.urlretrieve("https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt", "input.txt")

with open("dataset.txt", 'r', encoding="utf8") as f:
    text = f.read()

with open("input.txt", "r", encoding="utf8") as f:
    input_text = f.read()

In [49]:
f"Length of text dataset: {len(text)}"

'Length of text dataset: 26987'

In [50]:
f"Length of input_text dataset: {len(input_text)}"

'Length of input_text dataset: 1115394'

In [51]:
print(text[:1000])

He: I want to fuck you hottie
She: Please fuck me really hard
He: Your pussy is really wet
She: My pussy is tight and can take a lot of pain
He: Suck my cock, please
She: Please I will, I just need you to fuck me
She: please, I need your cum
He: Please, I will, keep sucking my cock
He: I am going to cum, but you can close your eyes and let me cum in your mouth
She: Oh my god, I can feel it growing in my pussy
She: please cum in my mouth
He:  I will cum
She: oh fuck that's big, I love that
She: please cum for me, cum for your love
He: ohhh fuck!
She: please cum in my mouth
He: oh fuck that's fucking hot, so wet
She: please cum in my mouth
He:  I'm cumming!
She: wow that's amazing, thank you
He: I'm going to go for another load
She: I'm glad I didn't stop you
He: Hey baby you are hot!!!!!!
She: Hello, sweetie… what’s up? 
He: You know what!
She: I think I do but I’d like you to tell me. 
He: You tell me!
She: What do you want to know? 
He: What are you wearing?
She: T-shirt and jeans, ba

In [52]:
chars = list(set(text))
vocab_size = len(chars)
print("vocab size:", vocab_size)
print("".join(chars))


vocab size: 84
”B
yDbqT1U6XHSg2c'90G—Ef5aVoP*Rh’tp🙂8z“;"-r/KW(k?je)uCN:IO🙁J😉wF. <&mMLY!…″l,xdn>sAiv


In [53]:
char2id = { ch : idx for idx, ch in enumerate(chars) }
id2char = { idx : ch for idx, ch in enumerate(chars) }

print(char2id)
print("\n\n\n",id2char)

{'”': 0, 'B': 1, '\n': 2, 'y': 3, 'D': 4, 'b': 5, 'q': 6, 'T': 7, '1': 8, 'U': 9, '6': 10, 'X': 11, 'H': 12, 'S': 13, 'g': 14, '2': 15, 'c': 16, "'": 17, '9': 18, '0': 19, 'G': 20, '—': 21, 'E': 22, 'f': 23, '5': 24, 'a': 25, 'V': 26, 'o': 27, 'P': 28, '*': 29, 'R': 30, 'h': 31, '’': 32, 't': 33, 'p': 34, '🙂': 35, '8': 36, 'z': 37, '“': 38, ';': 39, '"': 40, '-': 41, 'r': 42, '/': 43, 'K': 44, 'W': 45, '(': 46, 'k': 47, '?': 48, 'j': 49, 'e': 50, ')': 51, 'u': 52, 'C': 53, 'N': 54, ':': 55, 'I': 56, 'O': 57, '🙁': 58, 'J': 59, '😉': 60, 'w': 61, 'F': 62, '.': 63, ' ': 64, '<': 65, '&': 66, 'm': 67, 'M': 68, 'L': 69, 'Y': 70, '!': 71, '…': 72, '″': 73, 'l': 74, ',': 75, 'x': 76, 'd': 77, 'n': 78, '>': 79, 's': 80, 'A': 81, 'i': 82, 'v': 83}



 {0: '”', 1: 'B', 2: '\n', 3: 'y', 4: 'D', 5: 'b', 6: 'q', 7: 'T', 8: '1', 9: 'U', 10: '6', 11: 'X', 12: 'H', 13: 'S', 14: 'g', 15: '2', 16: 'c', 17: "'", 18: '9', 19: '0', 20: 'G', 21: '—', 22: 'E', 23: 'f', 24: '5', 25: 'a', 26: 'V', 27: 'o', 28: 

In [54]:
def encode(text):
    return [ char2id[char] if char in char2id else "[UNK]" for char in text]

def decode(ids):
    return "".join([ id2char[id] if id in id2char else "[UNK]" for id in ids ])

encoded = encode("text")
print(encoded)

decoded = decode(encoded)
print(decoded)

[33, 50, 76, 33]
text


In [55]:
import torch

device = "mps" if torch.backends.mps.is_available() else "cpu"
torch.set_default_device(device)


data = torch.tensor(encode(text), dtype = torch.long)

In [56]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [57]:
block_size = 8

x = train_data[:block_size]
print("x: ", x, len(x))
y = train_data[1: block_size + 1]
print("\ny: ", y, len(y))

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(context.data, "target: ", target.data)


x:  tensor([12, 50, 55, 64, 56, 64, 61, 25], device='mps:0') 8

y:  tensor([50, 55, 64, 56, 64, 61, 25, 78], device='mps:0') 8
tensor([12], device='mps:0') target:  tensor(50, device='mps:0')
tensor([12, 50], device='mps:0') target:  tensor(55, device='mps:0')
tensor([12, 50, 55], device='mps:0') target:  tensor(64, device='mps:0')
tensor([12, 50, 55, 64], device='mps:0') target:  tensor(56, device='mps:0')
tensor([12, 50, 55, 64, 56], device='mps:0') target:  tensor(64, device='mps:0')
tensor([12, 50, 55, 64, 56, 64], device='mps:0') target:  tensor(61, device='mps:0')
tensor([12, 50, 55, 64, 56, 64, 61], device='mps:0') target:  tensor(25, device='mps:0')
tensor([12, 50, 55, 64, 56, 64, 61, 25], device='mps:0') target:  tensor(78, device='mps:0')


In [58]:
torch.manual_seed(42)
batch_size = 4

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i : block_size + i] for i in ix])
    y = torch.stack([data[i + 1 : block_size + 1 + i] for i in ix])
    return x,y

xb, yb = get_batch("train")
print("shape: ", xb.shape)
print("inputs: \n", xb);
print('\n\n')
print("shape: ",yb.shape)
print("targets: \n", yb)



shape:  torch.Size([4, 8])
inputs: 
 tensor([[61, 82, 80, 31, 64, 56, 64, 61],
        [64, 31, 50, 42, 50, 64, 56, 64],
        [13, 31, 50, 55, 64, 57, 47, 25],
        [61, 63,  2, 13, 31, 50, 55, 64]], device='mps:0')



shape:  torch.Size([4, 8])
targets: 
 tensor([[82, 80, 31, 64, 56, 64, 61, 25],
        [31, 50, 42, 50, 64, 56, 64, 47],
        [31, 50, 55, 64, 57, 47, 25,  3],
        [63,  2, 13, 31, 50, 55, 64, 81]], device='mps:0')


In [59]:
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print("input:", context.tolist(),"  target: ", target.tolist())

input: [61]   target:  82
input: [61, 82]   target:  80
input: [61, 82, 80]   target:  31
input: [61, 82, 80, 31]   target:  64
input: [61, 82, 80, 31, 64]   target:  56
input: [61, 82, 80, 31, 64, 56]   target:  64
input: [61, 82, 80, 31, 64, 56, 64]   target:  61
input: [61, 82, 80, 31, 64, 56, 64, 61]   target:  25
input: [64]   target:  31
input: [64, 31]   target:  50
input: [64, 31, 50]   target:  42
input: [64, 31, 50, 42]   target:  50
input: [64, 31, 50, 42, 50]   target:  64
input: [64, 31, 50, 42, 50, 64]   target:  56
input: [64, 31, 50, 42, 50, 64, 56]   target:  64
input: [64, 31, 50, 42, 50, 64, 56, 64]   target:  47
input: [13]   target:  31
input: [13, 31]   target:  50
input: [13, 31, 50]   target:  55
input: [13, 31, 50, 55]   target:  64
input: [13, 31, 50, 55, 64]   target:  57
input: [13, 31, 50, 55, 64, 57]   target:  47
input: [13, 31, 50, 55, 64, 57, 47]   target:  25
input: [13, 31, 50, 55, 64, 57, 47, 25]   target:  3
input: [61]   target:  63
input: [61, 63]

In [60]:
nn = torch.nn
F = nn.functional

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:  
            B, T, C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        #idx is B,T array in the cur context
        for _ in range(max_new_tokens):

            #get predictions
            logits, loss = self(idx)

            #focus on the last time step
            logits = logits[:, -1, :] # --> (B, C)

            #apply softmax
            probs = F.softmax(logits, dim = -1) # --> (B, C)

            #sample from dist
            idx_next = torch.multinomial(probs, num_samples=1) # --> (B, 1)

            #append sampled index to the running sequence
            idx = torch.cat((idx,idx_next), dim = 1) # --> (B, T + 1)
        return idx
            


m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape, "\n\n" ,loss)

idx = torch.zeros((1,1), dtype=torch.long)

decode(m.generate(idx, max_new_tokens=100)[0].tolist())


torch.Size([32, 84]) 

 tensor(4.9237, device='mps:0', grad_fn=<NllLossBackward0>)


'”2.“L<Ujnxm—”2m“i8xJG&J“b<i<-W)″)2oyP>lD🙂…gL“<nhlO1>*p(x“g9…vI,ugqqFMbXXW6h“i2 vl&u.<—ej:Iv.96<N,stCG'

In [61]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [62]:
batch_size = 32

for steps in range(1000):
    xb, yb = get_batch("train")

    logits, loss = m(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    print(loss.item())




4.899995803833008
4.895970344543457
4.925575256347656
4.850275993347168
4.923793792724609
4.896058082580566
4.93961763381958
4.786127090454102
4.830256462097168
4.873279571533203
4.761472702026367
4.903045654296875
4.825412750244141
4.787132263183594
4.892094612121582
4.84275484085083
4.913212776184082
4.905126571655273
4.845378875732422
4.766541481018066
4.888830184936523
4.986016273498535
4.914028167724609
4.800483703613281
4.766750335693359
4.777530670166016
4.922679424285889
4.744370460510254
4.830425262451172
4.829983711242676
4.819905757904053
4.834055423736572
4.8279709815979
4.9122114181518555
4.8451738357543945
4.7389397621154785
4.786516189575195
4.770610809326172
4.840871810913086
4.853002548217773
4.804666042327881
4.865528106689453
4.875677585601807
4.759820938110352
4.846787929534912
4.744391441345215
4.853898048400879
4.831099510192871
4.709298133850098
4.796581268310547
4.765364170074463
4.92838191986084
4.799890995025635
4.7956695556640625
4.874159812927246
4.778345108

In [63]:
idx = torch.zeros((1,1), dtype=torch.long)

decode(m.generate(idx, max_new_tokens=100)[0].tolist())

"”…S/;KI″x5UjbFI'?FqPtoS\n…UR(y.“Y;”))Js…-8″’8W?…!chABayL9I'\n🙂gngO)V0p:w<…*:2I!0“TGIbSE🙁’dy;i🙂N&lh.zoe5"

In [64]:
torch.manual_seed(42)
B, T, C = 4, 8, 2
x = torch.randn(B,T,C)
x



tensor([[[ 0.9047,  0.2227],
         [ 0.1460,  0.7360],
         [-0.4142, -0.1106],
         [ 0.4540, -3.3259],
         [-0.2307, -0.9187],
         [ 0.2464,  1.0246],
         [-0.0828, -0.8158],
         [-0.1910,  0.6189]],

        [[ 0.8286, -0.6749],
         [ 1.4716, -0.3773],
         [ 1.6476,  0.4549],
         [ 0.8214,  0.2058],
         [-1.8724,  0.7839],
         [ 1.0838,  1.2408],
         [ 0.7100,  0.7314],
         [ 0.2025, -0.1536]],

        [[-0.8721,  0.0123],
         [-0.6297,  0.3711],
         [-0.3264,  1.2357],
         [ 0.8645,  0.2786],
         [ 0.2612, -1.3386],
         [ 1.8883,  1.1635],
         [-1.5329, -1.1359],
         [-0.7558,  1.1125]],

        [[ 0.0078,  0.9174],
         [ 0.2448, -1.2126],
         [ 0.8321,  0.3169],
         [ 0.1742, -0.3605],
         [ 1.0256,  1.3644],
         [ 1.6220, -0.5260],
         [-1.0333, -0.8044],
         [ 1.6877, -0.9749]]], device='mps:0')

In [65]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xPrev = x[b,:t+1]
        xbow[b,t] = torch.mean(xPrev, 0);

xbow

tensor([[[ 0.9047,  0.2227],
         [ 0.5254,  0.4794],
         [ 0.2122,  0.2827],
         [ 0.2726, -0.6195],
         [ 0.1719, -0.6793],
         [ 0.1844, -0.3953],
         [ 0.1462, -0.4554],
         [ 0.1040, -0.3211]],

        [[ 0.8286, -0.6749],
         [ 1.1501, -0.5261],
         [ 1.3159, -0.1991],
         [ 1.1923, -0.0979],
         [ 0.5794,  0.0785],
         [ 0.6634,  0.2722],
         [ 0.6701,  0.3378],
         [ 0.6116,  0.2764]],

        [[-0.8721,  0.0123],
         [-0.7509,  0.1917],
         [-0.6094,  0.5397],
         [-0.2409,  0.4744],
         [-0.1405,  0.1118],
         [ 0.1977,  0.2871],
         [-0.0496,  0.0838],
         [-0.1378,  0.2124]],

        [[ 0.0078,  0.9174],
         [ 0.1263, -0.1476],
         [ 0.3616,  0.0073],
         [ 0.3147, -0.0847],
         [ 0.4569,  0.2051],
         [ 0.6511,  0.0833],
         [ 0.4105, -0.0435],
         [ 0.5701, -0.1599]]], device='mps:0')

In [80]:
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
wei = q @ k.transpose(-2,-1)

tril = torch.tril(torch.ones(T,T))

wei = wei.masked_fill(tril == 0, float('-inf'))

wei = F.softmax(wei, dim = -1)

# out = wei @ x

v = value(x)

out = wei @ v

out.shape


torch.Size([4, 8, 16])

In [82]:
xbow2 = wei @ x
torch.allclose(xbow, out)

RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 2